In [8]:
import numpy as np
list1=[[4,5,24,34,545,435,34,5],[345,34,5,34,5345,34,534,5]]
ar1=np.array(list1)
print(ar1)

[[   4    5   24   34  545  435   34    5]
 [ 345   34    5   34 5345   34  534    5]]


In [12]:
print(ar1.shape)
print(ar1.size)

(2, 8)
16


In [23]:
# array produce
ar1=np.arange(4.5,10,0.5) #same like the range funtion but also produce the float numbers  
print(ar1)
ar2 =np.linspace(0,30,10)
print(ar2)  
# by zeros(simaler to this there are "ones" and "empety")
ar3= np.zeros(10)
print(ar3)
ar3= np.zeros((5,7))
print(ar3)
ar3= np.zeros((4,5,8))
print(ar3)

#(simaler to this there are "ones" and "empety")
#ones
ar3= np.ones((5,7))
print(ar3)
#empty
ar3= np.empty((5,7))
print(ar3)

[4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 

In [25]:
ar3= np.empty((5,7))
print(ar3*43 )

[[43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43.]
 [43. 43. 43. 43. 43. 43. 43.]]


In [28]:
#eye for squre matrix(identric matrix)
ar1=np.eye(5)
print(ar1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
#random in array or numpay
ar1=np.random.randn(3,4)#randn means the mean of numbers are always 0 and sd of that numbers are 1 
print(ar1)
ar2=np.random.randint(10,100,(5,8))
print(ar2)
ar2.reshape(8,5)#if not know the other facter just put -1(any nagative number in the dimention)
ar2.reshape(5,-4)#if not know the other facter just put -1(any nagative number in the dimention)
 

[[ 1.01363146  0.12708006  0.93606428 -1.91511979]
 [-0.23957665 -0.39149813 -0.92525411 -2.10358668]
 [ 0.82524948 -1.55526371 -0.65110955 -0.64989212]]
[[35 45 10 73 25 70 94 96]
 [76 92 48 25 90 30 50 61]
 [23 15 10 44 92 89 68 15]
 [86 54 44 58 84 84 67 89]
 [65 75 97 76 64 29 33 21]]


array([[35, 45, 10, 73, 25, 70, 94, 96],
       [76, 92, 48, 25, 90, 30, 50, 61],
       [23, 15, 10, 44, 92, 89, 68, 15],
       [86, 54, 44, 58, 84, 84, 67, 89],
       [65, 75, 97, 76, 64, 29, 33, 21]])

In [34]:
ar2

array([[35, 45, 10, 73, 25, 70, 94, 96],
       [76, 92, 48, 25, 90, 30, 50, 61],
       [23, 15, 10, 44, 92, 89, 68, 15],
       [86, 54, 44, 58, 84, 84, 67, 89],
       [65, 75, 97, 76, 64, 29, 33, 21]])

In [42]:
ar2[...,[3,5]]#(use ... for selecting the last range (for selecting the complete ))

array([[73, 70],
       [25, 30],
       [44, 89],
       [58, 84],
       [76, 29]])

In [43]:
# we use @ for the metrix multiplication 
#use array.T to transpost the matrix 
# numpy array broad casting 

# example of broadcasting 
l1=[4,53,3434,3443,4324,232,323,233]
print(ar2)
print(ar2+l1)

[[35 45 10 73 25 70 94 96]
 [76 92 48 25 90 30 50 61]
 [23 15 10 44 92 89 68 15]
 [86 54 44 58 84 84 67 89]
 [65 75 97 76 64 29 33 21]]
[[  39   98 3444 3516 4349  302  417  329]
 [  80  145 3482 3468 4414  262  373  294]
 [  27   68 3444 3487 4416  321  391  248]
 [  90  107 3478 3501 4408  316  390  322]
 [  69  128 3531 3519 4388  261  356  254]]


In [44]:
np.sqrt(ar2)

array([[5.91607978, 6.70820393, 3.16227766, 8.54400375, 5.        ,
        8.36660027, 9.69535971, 9.79795897],
       [8.71779789, 9.59166305, 6.92820323, 5.        , 9.48683298,
        5.47722558, 7.07106781, 7.81024968],
       [4.79583152, 3.87298335, 3.16227766, 6.63324958, 9.59166305,
        9.43398113, 8.24621125, 3.87298335],
       [9.2736185 , 7.34846923, 6.63324958, 7.61577311, 9.16515139,
        9.16515139, 8.18535277, 9.43398113],
       [8.06225775, 8.66025404, 9.8488578 , 8.71779789, 8.        ,
        5.38516481, 5.74456265, 4.58257569]])

In [46]:
ar2.flatten()# convert the all data into a single row 1d array(or in the list)

array([35, 45, 10, 73, 25, 70, 94, 96, 76, 92, 48, 25, 90, 30, 50, 61, 23,
       15, 10, 44, 92, 89, 68, 15, 86, 54, 44, 58, 84, 84, 67, 89, 65, 75,
       97, 76, 64, 29, 33, 21])

In [47]:
#numpy part 2 hindi.ipynb for the diffrent functions new one 

In [51]:
ar2.repeat(4)
np.repeat(ar2,3)

array([35, 35, 35, 45, 45, 45, 10, 10, 10, 73, 73, 73, 25, 25, 25, 70, 70,
       70, 94, 94, 94, 96, 96, 96, 76, 76, 76, 92, 92, 92, 48, 48, 48, 25,
       25, 25, 90, 90, 90, 30, 30, 30, 50, 50, 50, 61, 61, 61, 23, 23, 23,
       15, 15, 15, 10, 10, 10, 44, 44, 44, 92, 92, 92, 89, 89, 89, 68, 68,
       68, 15, 15, 15, 86, 86, 86, 54, 54, 54, 44, 44, 44, 58, 58, 58, 84,
       84, 84, 84, 84, 84, 67, 67, 67, 89, 89, 89, 65, 65, 65, 75, 75, 75,
       97, 97, 97, 76, 76, 76, 64, 64, 64, 29, 29, 29, 33, 33, 33, 21, 21,
       21])